---
title: "correlation_heatmap"
author: "TS"
date: "12/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 12, fig.height = 7)
library(tidyverse)
library(ggrepel)

theme_tomas <- function(base_size = 15, base_family = "sans"){
  theme_light(base_size = base_size, base_family = base_family) %+replace%
    theme(
      plot.title = element_text(color = 'black', hjust = 0, size = base_size, vjust = 0, margin = margin(0,0,0.4,0, 'cm')),
      plot.subtitle = element_text(color = 'black',size = base_size, hjust = 0),
      #axis.title = element_text(color = 'black', size = 14),
      #axis.text = element_text(color = rgb(105, 105, 105, maxColorValue = 255),size = 14),
      
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.background = element_rect(color = 'white'),
      panel.border = element_blank(), 
      axis.line = element_line(colour = "black", size = 0.1),
      # for facets
      strip.text.x = element_text(size = base_size, colour = "black", margin = margin(0.05,0.05,0.05,0.05,'cm')), 
      strip.background =element_rect(fill="gray90", color = 'gray85', linetype = NULL),
      complete = TRUE
    )
}
```

```{r}
library(viridis)
correlations = read_csv('../steps/corrs.csv')
correlations = correlations %>% 
  gather(`0`:`440`, key = Feature, value = Correlation)

correlations$Feature <- as.numeric(correlations$Feature)
```


```{r}
correlations %>% 
  ggplot() +
  geom_tile(aes(X1, Feature, fill = Correlation)) + 
  theme_tomas(base_size = 20) + 
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_viridis() +
  labs(y = 'Feature ID', x = 'Feature ID', fill = 'Absolute\nCorrelation') +
  #geom_text(aes(x = 165, y = 80, label = 'PC/SM')) + 
  annotate('text', x = 165, y = 80, label = 'PC/SM', size = 7, color = 'white') + 
  geom_segment(aes(x = 120, xend = 140, y = 80, yend = 80), color = 'white', arrow = arrow(length = unit(0.2, "cm"))) + 
  
  annotate('text', x = 300, y = 250, label = 'Sugars', size = 7, color = 'white') +
  geom_segment(aes(x = 310, xend = 300, y = 306, yend = 270), color = 'white', arrow = arrow(length = unit(0.2, "cm"))) + 
  annotate('text', x = 210, y = 380, label = 'Sugars and\nFatty Acids', size = 7, color = 'white') +
  geom_segment(aes(x = 370, xend = 260, y = 380, yend = 380), color = 'white', arrow = arrow(length = unit(0.2, "cm")))

#ggsave('../plots/correlations.png', width = 12, height = 10, dpi = 200)
```